/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ua.gov.pv.defektplet.ui;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JFrame;
import ua.gov.pv.defektplet.drawing.DrawRailway;
import ua.gov.pv.defektplet.drawing.GraphicsCharacteristics;
import ua.gov.pv.defektplet.helper.IntervalInformation;

/**
 *
 * @author ПГМ
 */
public class ChooseForm extends javax.swing.JFrame {

    /**
     * Creates new form ChooseForm
     */
    private IntervalInformation[] ii;

    public ChooseForm() {
        initComponents();
    }
    

    ChooseForm(IntervalInformation... ii) {
        initComponents();
        this.ii = ii;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbDefekts = new javax.swing.JCheckBox();
        cbGovVelocity = new javax.swing.JCheckBox();
        cbTR = new javax.swing.JCheckBox();
        bConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbDefekts.setText("Дефекті");

        cbGovVelocity.setText("Скорость");

        cbTR.setText("ВВ");

        bConfirm.setText("Confirm");
        bConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTR)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbGovVelocity)
                        .addGap(44, 44, 44)
                        .addComponent(bConfirm))
                    .addComponent(cbDefekts))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbDefekts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGovVelocity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bConfirm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbTR)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConfirmActionPerformed
        //for (IntervalInformation i : ii) {
        IntervalInformation i = new IntervalInformation("Дарниця - Полтава", 137, 0, 141, 1000, 1, "Ліва");    
        DrawRailway dr = new DrawRailway(new GraphicsCharacteristics(1000, 50, 10, 500), i);
        dr.draw();
        JFrame jf=new JFrame();
        Dimension d = jf.getMaximumSize();
        jf.setSize(d.width, d.height);
        ImagePanel ip = new ImagePanel(dr.getbImage().get(0));
        ip.paintComponent(getGraphics());
        jf.setContentPane(ip);
        jf.setVisible(true);
            
      //  }
    }//GEN-LAST:event_bConfirmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConfirm;
    private javax.swing.JCheckBox cbDefekts;
    private javax.swing.JCheckBox cbGovVelocity;
    private javax.swing.JCheckBox cbTR;
    // End of variables declaration//GEN-END:variables
}
